[package]
name = "farm-operator-1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.6"
axum-server = { version = "0.4", features = ["tls-rustls"] }
k8s-openapi = { version = "0.17", features = ["v1_24"] }
rcgen = "0.10"
tokio = { version = "1", features = ["full"] }
