name: Publish

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '**/Dockerfile'
      - '**/.docker*'

jobs:
  build-and-publish:
    strategy:
      matrix:
        step: ['1', '2']
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./step-{{ matrix.step }}/Dockerfile
          push: true
          build-args: |
            GITHUB_SHA=${{ github.sha }}
          tags: ghcr.io/metalbear-co/farm-operator:{{ matrix.step }}-latest
